site_title: "LACK Knowledge Graph"
base_url: "/lack"
nav:
  - label: "Home"
    file: "index.md"
  - label: "About"
    file: "about.md"
  - label: "Knowledge Graph"
    file: "knowledge-graph.md"
  - label: "Ontology"
    file: "ontology.md"
  - label: "Download"
    file: "download.md"
  - label: "Case Studies"
    file: "case-studies.md"
  - label: "Explore"
    url: "static/explore.html"
